# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: xin
  CLOUD_SQL_PASSWORD: 1234
  CLOUD_SQL_DATABASE_NAME: demo
  CLOUD_SQL_CONNECTION_NAME: ad-2021-01:europe-west2:advanceddevelopment
# [END gae_python37_cloudsql_config]